hwi_oauth:
    firewall_names: [secured_area]
    resource_owners:
        github:
            type:          github
            client_id:     '%env(GITHUB_CLIENT_ID)%'
            client_secret: '%env(GITHUB_CLIENT_SECRET)%'
            scope:         'user:email,public_repo'
